ajax_app/config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  resources :recipes, only: [:index, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ajax_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ajax_app/app/models/recipe.rb
class Recipe < ApplicationRecord
end

ajax_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

ajax_app/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
    @recipe = Recipe.new
  end

  def create
    Recipe.create(recipe_params)
    @recipes = Recipe.all
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :body)
  end
end

ajax_app/app/helpers/application_helper.rb
module ApplicationHelper
end

ajax_app/app/helpers/recipes_helper.rb
module RecipesHelper
end

ajax_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxAppDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="#">Recipegram</a>
    </nav>
    <%= yield %>
  </body>
</html>

ajax_app/app/views/recipes/_recipes.html.erb
<% recipes.each do |recipe| %>
  <div class="card mb-1">
    <div class="card-body">
        <p class="card-text"><%= recipe.title %></p>
        <p class="card-text"><small><%= simple_format recipe.body %></small></p>
    </div>
  </div>
<% end %>

ajax_app/app/views/recipes/create.js.erb
$("textarea").val("");
$("input").val("");
$('#exampleModal').modal('hide')
$('.recipes').html("<%= escape_javascript(render 'recipes', recipes: @recipes) %>")

ajax_app/app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

ajax_app/app/views/recipes/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-3">
      <button type="button" class="btn btn-primary w-100" data-toggle="modal" data-target="#exampleModal">
        新規投稿
      </button>
    </div>
    <div class="col-9">
　　　<%= render 'recipes',recipes: @recipes %>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">新規投稿</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for @recipe, remote: true do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :title, "レシピ" %>
            <%= f.text_field :title, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :body, "作り方" %>
            <%= f.text_area :body, class:"form-control" %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
          <%= f.submit "投稿する", class:"btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

ajax_app/app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

ajax_app/app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @recipe.body %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>